### ISSUE TITLE
Inputs should not be included in this repository

### ISSUE THREAD

**Issue by brayevalerien** [vlang/adventofcode#47]
The author of the Advent of Code explicitly asks people to not include the puzzle inputs in public repositories [here](https://adventofcode.com/2023/about):

> Can I copy/redistribute part of Advent of Code? Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or **your inputs**.

**Comment by JalonSolov** [comment]
Correct, it shouldn't include **your** inputs.  The inputs in the repo are the example inputs everyone sees when they see the puzzles.

**Comment by brayevalerien** [comment]
I see, it makes more sense now. Thanks for answering.
