### ISSUE TITLE
Input file standards

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/adventofcode#6]
We should file a standard for input files for who created it first. Since inputs can be very different, we should have a common input file that:
1, Fully matches original example input
- - No whitespace trimming
- - No additional line
- - No personal-specific input allowed to be example input file

3, If there are multiple example input introduced, select one and suffix its file name with `_partX` to specify two different example inputs for a day, then follow citerion1.
4, input file's name should relates to corresponding AoC problem.

**Comment by spytheman** [comment]
Seems reasonable. Please edit the README to add these.

**Comment by ChAoSUnItY** [comment]
Ok, I'll fix the input formats first then edit README
